web:
  restart: always
  build: .
  container_name: clusiana
  command: npm start
  links:
   - db
  ports:
   - "3000:3000"
   - "5858:5858"
   - "35729:35729"
  environment:
   - NODE_ENV=development
  volumes:
   - ./:/opt/clusiana
   - /opt/clusiana/node_modules
   - /opt/clusiana/public
   - /opt/clusiana/uploads
